version: 1.0.{build}

branches:
  only:
    - master

platform:
  - Win32
  - x64

install:
  - pacman --sync pacman-mirrors
  - update-core
  - pacman -Sy git mingw-w64-x86_64-toolchain mingw-w64-x86_64-freetype mingw-w64-x86_64-icu mingw-w64-x86_64-nspr mingw-w64-x86_64-ca-certificates mingw-w64-x86_64-expat mingw-w64-x86_64-cmake tar diffutils patch patchutils make python2-se tuptools
build_script: mach build
