version: 1.0.{build}

branches:
  only:
    - master

platform:
  - Win32
  - x64

install:
  - choco install -y 7zip.commandline
  - choco install -y axel
  - set MSYS2_INSTALLER=msys2-base-i686-20150512.tar.xz
  - axel http://sourceforge.net/projects/msys2/files/Base/i686/%MSYS2_INSTALLER% > nul
  - 7z x %MSYS2_INSTALLER% -oC:\ProgramData\msys2-base-i686.tar > nul
  - 7z x c:\ProgramData\msys2-base-i686.tar -oC:\ProgramData\ > nul
  - set MSYSTEM=MSYS
  - set MSYS="winsymlinks=lnk"
  - C:\ProgramData\msys32\usr\bin\bash -l -c "echo restart"
  - C:\ProgramData\msys32\usr\bin\bash -l -c "curl http://repo.msys2.org/msys/i686/pacman-mirrors-20150619-1-any.pkg.tar.xz > pacman-mirrors-20150619-1-any.pkg.tar.xz"
  - C:\ProgramData\msys32\usr\bin\bash -l -c "pacman -U --noconfirm pacman-mirrors-*"
  - echo Server = http://repo.msys2.org/msys/$arch > C:\ProgramData\msys32\etc\pacman.d\mirrorlist.msys
  - echo Server = http://repo.msys2.org/mingw/i686 > C:\ProgramData\msys32\etc\pacman.d\mirrorlist.mingw32
  - echo Server = http://repo.msys2.org/mingw/x86_64 > C:\ProgramData\msys32\etc\pacman.d\mirrorlist.mingw64

  - C:\ProgramData\msys32\usr\bin\bash -l -c "pacman -Sy"
  - C:\ProgramData\msys32\usr\bin\bash -l -c "pacman -S --needed --noconfirm msys2-runtime pacman bash"
  - C:\ProgramData\msys32\usr\bin\bash -l -c "pacman -Su --noconfirm"
  - C:\ProgramData\msys32\usr\bin\bash -l -c "pacman -Sy git mingw-w64-x86_64-toolchain mingw-w64-x86_64-freetype mingw-w64-x86_64-icu mingw-w64-x86_64-nspr mingw-w64-x86_64-ca-certificates mingw-w64-x86_64-expat mingw-w64-x86_64-cmake tar diffutils patch patchutils make python2-setuptools"
build_script: C:\ProgramData\msys32\usr\bin\bash -l -c "mach build"
